CFLAGS_mtk_lp_kernfs.o := -I$(src)
CFLAGS_mtk_lp_sysfs_kernfs.o := -I$(src)
CFLAGS_mtk_lp_sysfs.o := -I$(src)
CFLAGS_mtk_idle_sysfs.o := -I$(src)
CFLAGS_mtk_lp_sysfs_procfs.o := -I$(src)

obj-y += mtk_lp_kernfs.o
obj-y += mtk_lp_sysfs.o
obj-y += mtk_idle_sysfs.o
obj-y += mtk_lp_sysfs_procfs.o
