#!/usr/bin/env python3
"""Resolve BTF_ID symbols in a linked vmlinux ELF.

Replacement for the upstream tools/bpf/resolve_btfids tool, which is not
carried in this tree. It reads the .BTF type information of the vmlinux ELF
via bpftool (any modern libbpf handles both 24- and 32-byte BTF headers),
locates the __BTF_ID__* symbols placed in the .BTF_ids section by the
BTF_ID_LIST macros, and patches the BTF type ids in place.

Only the plain per-type symbol form (__BTF_ID__<kind>__<name>) generated by
BTF_ID() is handled; set8-style kfunc sets are not used by this tree.
"""

import os
import re
import struct
import subprocess
import sys
import tempfile

OBJCOPY = os.environ.get("OBJCOPY") or os.environ.get("LLVM_OBJCOPY",
                                                      "llvm-objcopy")
READELF = os.environ.get("READELF") or os.environ.get("LLVM_READELF",
                                                      "llvm-readelf")
BPFTOOL = os.environ.get("BPFTOOL", "bpftool")

KIND_MAP = {
    "struct": "STRUCT",
    "union": "UNION",
    "enum": "ENUM",
    "fwd": "FWD",
    "typedef": "TYPEDEF",
    "func": "FUNC",
}


def die(msg):
    sys.stderr.write("resolve_btfids: %s\n" % msg)
    sys.exit(1)


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        die("%s failed: %s" % (cmd[0], r.stderr.strip()))
    return r.stdout


def read_section(elf, name):
    fd, tmp = tempfile.mkstemp()
    os.close(fd)
    try:
        run([OBJCOPY, "-O", "binary", "--only-section=" + name, elf, tmp])
        data = open(tmp, "rb").read()
    finally:
        os.unlink(tmp)
    if not data:
        die("section %s is empty or missing" % name)
    return data


def write_section(elf, name, data):
    fd, tmp = tempfile.mkstemp()
    try:
        open(tmp, "wb").write(data)
        run([OBJCOPY, "--update-section", "%s=%s" % (name, tmp), elf])
    finally:
        os.unlink(tmp)


def section_addr(elf, name):
    out = run([READELF, "-SW", elf])
    for line in out.splitlines():
        fields = line.split()
        if name in fields:
            i = fields.index(name)
            try:
                return int(fields[i + 2], 16)
            except (IndexError, ValueError):
                pass
    die("section %s not found in readelf output" % name)


def btf_type_map(elf):
    """Return {(kind, name): id} parsed by bpftool (robust against any
    BTF header layout the vendored code cannot handle)."""
    out = run([BPFTOOL, "btf", "dump", "file", elf])
    types = {}
    for line in out.splitlines():
        m = re.match(r"\[(\d+)\] (\w+) '([^']*)'", line)
        if not m:
            continue
        tid, kind, name = int(m.group(1)), m.group(2), m.group(3)
        types.setdefault((kind, name), tid)
    if not types:
        die("bpftool produced no type information")
    return types


def main():
    if len(sys.argv) < 2:
        die("usage: resolve_btfids.py <elf-file>")
    elf = sys.argv[1]

    btf_ids_addr = section_addr(elf, ".BTF_ids")

    want = []
    seen = set()
    for line in run([READELF, "-sW", elf]).splitlines():
        m = re.match(r"\s*\d+:\s+([0-9a-fA-F]+)\s+\d+\s+OBJECT\s+\S+\s+\S+"
                     r"\s+(\S+)\s+(\S+)", line)
        if not m:
            continue
        value, name = int(m.group(1), 16), m.group(3)
        sm = re.match(r"__BTF_ID__(struct|union|enum|fwd|typedef|func)"
                      r"__([A-Za-z0-9_]+?)(?:__\d+)?$", name)
        if not sm:
            continue
        off = value - btf_ids_addr
        key = (off, sm.group(1), sm.group(2))
        if key in seen:
            continue
        seen.add(key)
        want.append((off, key[1], key[2], name))

    if not want:
        print("resolve_btfids: no BTF_ID symbols to resolve")
        return

    types = btf_type_map(elf)
    patched = bytearray(read_section(elf, ".BTF_ids"))
    unresolved = []
    for off, kind, name, sym in want:
        tid = types.get((KIND_MAP[kind], name))
        if tid is None:
            unresolved.append(sym)
            continue
        if off + 4 > len(patched):
            die("symbol %s beyond .BTF_ids section" % sym)
        struct.pack_into("<I", patched, off, tid)

    if unresolved:
        for sym in unresolved:
            sys.stderr.write("FAILED unresolved symbol %s\n" %
                             sym.replace("__BTF_ID__", ""))
        sys.exit(1)

    write_section(elf, ".BTF_ids", bytes(patched))
    print("resolve_btfids: resolved %d symbols" % len(want))


if __name__ == "__main__":
    main()
